%YAML:1.0

########################################################
# IMU AUTOPILOT
########################################################

# imu0:

#   T_i_b:
#     - [1.0, 0.0, 0.0, 0.0]
#     - [0.0, 1.0, 0.0, 0.0]
#     - [0.0, 0.0, 1.0, 0.0]
#     - [0.0, 0.0, 0.0, 1.0]
#   accelerometer_noise_density:  0.000976199973245127  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
#   accelerometer_random_walk: 5.08299623437513e-05     # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
#   gyroscope_noise_density: 0.00011305741939005275     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
#   gyroscope_random_walk:  3.2529151246317528e-06      # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
#   rostopic: /mavros/imu/data
#   time_offset: 0.0
#   update_rate: 50.0
#   # three different modes supported:
#   # "calibrated" (same as "kalibr"), "kalibr", "rpng"
#   model: "kalibr"
#   # how to get from Kalibr imu.yaml result file:
#   #   - Tw is imu0:gyroscopes:M:
#   #   - R_IMUtoGYRO: is imu0:gyroscopes:M:
#   #   - Ta is imu0:accelerometers:M:
#   #   - R_IMUtoACC not used by Kalibr
#   #   - Tg is imu0:gyroscopes:A:
#   Tw:
#     - [ 1.0, 0.0, 0.0 ]
#     - [ 0.0, 1.0, 0.0 ]
#     - [ 0.0, 0.0, 1.0 ]
#   R_IMUtoGYRO:
#     - [ 1.0, 0.0, 0.0 ]
#     - [ 0.0, 1.0, 0.0 ]
#     - [ 0.0, 0.0, 1.0 ]
#   Ta:
#     - [ 1.0, 0.0, 0.0 ]
#     - [ 0.0, 1.0, 0.0 ]
#     - [ 0.0, 0.0, 1.0 ]
#   R_IMUtoACC:
#     - [ 1.0, 0.0, 0.0 ]
#     - [ 0.0, 1.0, 0.0 ]
#     - [ 0.0, 0.0, 1.0 ]
#   Tg:
#     - [ 0.0, 0.0, 0.0 ]
#     - [ 0.0, 0.0, 0.0 ]
#     - [ 0.0, 0.0, 0.0 ]

########################################################
# IMU DVS CAMERA
########################################################

  T_i_b:
    - [1.0, 0.0, 0.0,  0.0]
    - [0.0, 0.0, -1.0, 0.0]
    - [0.0, 1.0, 0.0,  0.0]
    - [0.0, 0.0, 0.0,  1.0]
  accelerometer_noise_density:  0.0023635621949534913   # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 0.00038545022997460627     # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyroscope_noise_density: 0.0001295867886474796     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk:  6.126531020359285e-06       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  rostopic: /dvs/imu
  time_offset: 0.0
  update_rate: 800.0
  # three different modes supported:
  # "calibrated" (same as "kalibr"), "kalibr", "rpng"
  model: "kalibr"
  # how to get from Kalibr imu.yaml result file:
  #   - Tw is imu0:gyroscopes:M:
  #   - R_IMUtoGYRO: is imu0:gyroscopes:M:
  #   - Ta is imu0:accelerometers:M:
  #   - R_IMUtoACC not used by Kalibr
  #   - Tg is imu0:gyroscopes:A:
  Tw:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoGYRO:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Ta:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoACC:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Tg:
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]
